# Generated by Django 5.0 on 2023-12-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email: ')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
                ('date', models.CharField(max_length=255, verbose_name='Дата')),
            ],
        ),
    ]
