# Generated by Django 5.0 on 2023-12-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Заявка на бронь', 'verbose_name_plural': 'Заявки на брони'},
        ),
    ]
