# Generated by Django 5.0 on 2024-01-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='Photo_image_1', verbose_name='Фотография')),
                ('image_2', models.ImageField(upload_to='Photo_image_2', verbose_name='Фотография')),
                ('image_3', models.ImageField(upload_to='Photo_image_3', verbose_name='Фотография')),
                ('image_4', models.ImageField(upload_to='Photo_image_4', verbose_name='Фотография')),
                ('image_5', models.ImageField(upload_to='Photo_image_5', verbose_name='Фотография')),
                ('image_6', models.ImageField(upload_to='Photo_image_6', verbose_name='Фотография')),
                ('image_7', models.ImageField(upload_to='Photo_image_7', verbose_name='Фотография')),
                ('image_8', models.ImageField(upload_to='Photo_image_8', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Фотография к голерее',
                'verbose_name_plural': 'Фотографии к голерее',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галереи'},
        ),
    ]
