# Generated by Django 5.0 on 2024-01-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_photo_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='Reservation_logo', verbose_name='Логотип')),
                ('image_one', models.ImageField(upload_to='Reservation_image_one', verbose_name='Фотография')),
                ('image_two', models.ImageField(upload_to='Reservation_image_two', verbose_name='Фотография')),
            ],
        ),
    ]
