# Generated by Django 5.0 on 2024-01-01 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирование'},
        ),
    ]
