# Generated by Django 5.0 on 2023-12-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Slide_image', verbose_name='Фотография')),
                ('title', models.CharField(max_length=255, verbose_name='Название баннера')),
                ('description', models.TextField(verbose_name='Описание')),
                ('prise', models.CharField(max_length=255, verbose_name='Цена')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
            ],
        ),
    ]
