# Generated by Django 5.0 on 2023-12-30 11:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_slide_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image2', models.ImageField(upload_to='image2_Condition', verbose_name='Фотография')),
                ('image1', models.ImageField(upload_to='image1_Condition', verbose_name='Фотография')),
                ('descriptions', ckeditor.fields.RichTextField(max_length=255, verbose_name='Описание')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
            ],
        ),
        migrations.RemoveField(
            model_name='slide',
            name='image',
        ),
    ]
