# Generated by Django 5.0 on 2023-12-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_condition_remove_slide_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name': 'Комфортные условия', 'verbose_name_plural': 'Комфортные условия'},
        ),
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.ImageField(default=1, upload_to='Slide_image', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
