# Generated by Django 5.0 on 2023-12-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_condition_options_slide_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='News_image1', verbose_name='Фотография')),
                ('image_2', models.ImageField(upload_to='News_image2', verbose_name='Фотография')),
                ('image_3', models.ImageField(upload_to='News_image3', verbose_name='Фотография')),
                ('image_4', models.ImageField(upload_to='News_image4', verbose_name='Фотография')),
                ('image_5', models.ImageField(upload_to='News_image5', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.RemoveField(
            model_name='slide',
            name='image',
        ),
    ]
