# Generated by Django 5.0 on 2023-12-30 11:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_news_remove_slide_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_1', ckeditor.fields.RichTextField(verbose_name='Услуга номер -1')),
                ('image_1', models.ImageField(upload_to='Serevise_image', verbose_name='Фотография - 1')),
                ('description_2', ckeditor.fields.RichTextField(verbose_name='Услуга номер -2')),
                ('image_2', models.ImageField(upload_to='Serevise_image', verbose_name='Фотография - 2')),
                ('description_3', ckeditor.fields.RichTextField(verbose_name='Услуга номер -3')),
                ('image_3', models.ImageField(upload_to='Serevise_image', verbose_name='Фотография - 3')),
            ],
        ),
    ]
