# Generated by Django 5.0 on 2023-12-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Новости'},
        ),
    ]
