# Generated by Django 5.0 on 2023-12-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_service_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуги'},
        ),
    ]
