# Generated by Django 5.0 on 2023-12-30 13:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_service_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Boss_image', verbose_name='Фотогрфия')),
                ('title', models.CharField(max_length=255, verbose_name='Должность')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
        ),
    ]
