# Generated by Django 5.0 on 2023-12-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_boss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=255, verbose_name='Фотграфия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
        ),
    ]
