# Generated by Django 5.0 on 2023-12-30 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_comands'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comands',
            options={'verbose_name': 'Наша команда', 'verbose_name_plural': 'Наши команды'},
        ),
    ]
