# Generated by Django 5.0 on 2023-12-30 15:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_comands_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание к "О нас"')),
                ('adres', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Ваш: email.com')),
                ('instagram', models.URLField(verbose_name='Ваш: Instagram')),
                ('twitter', models.URLField(verbose_name='Ваш: Twitter')),
                ('you_tube', models.URLField(verbose_name='Ваш:You Tube')),
                ('facebook', models.URLField(verbose_name='Ваш: Facebook')),
            ],
        ),
    ]
