# Generated by Django 5.0 on 2023-12-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_ass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ass',
            options={'verbose_name': 'Основная настройка', 'verbose_name_plural': 'Основный настройки'},
        ),
    ]
