# Generated by Django 5.0 on 2023-12-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_ass_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ass',
            name='admin',
            field=models.CharField(default=1, max_length=255, verbose_name='Авторские права принадлежат'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ass',
            name='admin_url',
            field=models.URLField(default=1, verbose_name='URL - Разработчика'),
            preserve_default=False,
        ),
    ]
