# Generated by Django 5.0 on 2023-12-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_ass_admin_ass_admin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ass',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo_image', verbose_name='Логотип'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ass',
            name='phone_2',
            field=models.CharField(default=1, max_length=255, verbose_name='Телефонный номер для брони баннера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ass',
            name='phone_3',
            field=models.CharField(default=1, max_length=255, verbose_name='Телефонный номер для брони'),
            preserve_default=False,
        ),
    ]
