# Generated by Django 5.0 on 2023-12-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_ass_logo_ass_phone_2_ass_phone_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ass',
            name='logo',
            field=models.ImageField(upload_to='logo', verbose_name='Логотип'),
        ),
    ]
