# Generated by Django 5.0 on 2023-12-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_ass_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(verbose_name='URL - Видео о MerriGarden')),
            ],
            options={
                'verbose_name': 'Видео о MerriGarden',
                'verbose_name_plural': 'Видео о MerriGarden',
            },
        ),
    ]
