# Generated by Django 5.0 on 2023-12-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='comands',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='email.com:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comands',
            name='facebook',
            field=models.URLField(default=1, verbose_name='URL - Facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comands',
            name='instagram',
            field=models.URLField(default=1, verbose_name='URL - Instagram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comands',
            name='pinterest',
            field=models.URLField(default=1, verbose_name='URL - Pinterest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comands',
            name='profession',
            field=models.CharField(default=1, max_length=255, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comands',
            name='twitter',
            field=models.URLField(default=1, verbose_name='URL - Twitter'),
            preserve_default=False,
        ),
    ]
