# Generated by Django 5.0 on 2024-01-02 11:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_comands_email_comands_facebook_comands_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
